// src/components/dashboard/pickup/pickup-dashboard.tsx
"use client";

import { useMemo, useState } from "react";
import { format } from "date-fns";
import { ArrowDownToLine, ArrowUpFromLine, PackageCheck } from "lucide-react";
import { toast } from "sonner";
import { StatCard } from "@/components/shared/stat-card";
import { StatusBadge } from "@/components/shared/status-badge";
import { DataTable, type DataTableColumn } from "@/components/shared/data-table";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { cn } from "@/lib/utils";
import {
  pickupActivity as initialActivity,
  pickupInventory as initialInventory,
  pickupSummary,
  type PickupActivityEvent,
  type PickupInventoryItem,
} from "@/lib/mock/pickup";

const OVERDUE_THRESHOLD_DAYS = 3;

export function PickupDashboard() {
  const [inventory, setInventory] = useState<PickupInventoryItem[]>(initialInventory);
  const [activity, setActivity] = useState<PickupActivityEvent[]>(initialActivity);
  const [checkInId, setCheckInId] = useState("");

  const overdueCount = useMemo(
    () => inventory.filter((item) => item.daysWaiting > OVERDUE_THRESHOLD_DAYS).length,
    [inventory]
  );

  function handleCheckIn(event: React.FormEvent) {
    event.preventDefault();
    const trackingId = checkInId.trim().toUpperCase();
    if (!trackingId) {
      toast.error("Enter a tracking ID");
      return;
    }

    const newItem: PickupInventoryItem = {
      id: trackingId,
      recipientName: "Walk-in customer",
      phone: "N/A",
      dateArrived: new Date().toISOString(),
      daysWaiting: 0,
      status: "PENDING",
    };
    setInventory((current) => [newItem, ...current]);
    setActivity((current) => [
      {
        id: `${Date.now()}`,
        time: new Date().toISOString(),
        staff: "You",
        action: "Checked in",
        parcelId: trackingId,
        type: "in",
      },
      ...current,
    ]);
    toast.success(`Parcel ${trackingId} checked in`);
    setCheckInId("");
  }

  function handleHandOver(id: string) {
    setInventory((current) => current.filter((item) => item.id !== id));
    setActivity((current) => [
      {
        id: `${Date.now()}`,
        time: new Date().toISOString(),
        staff: "You",
        action: "Checked out",
        parcelId: id,
        type: "out",
      },
      ...current,
    ]);
    toast.success(`Parcel ${id} handed over`);
  }

  const columns: DataTableColumn<PickupInventoryItem>[] = [
    { key: "id", header: "Tracking ID", accessor: (row) => row.id },
    { key: "recipientName", header: "Recipient", accessor: (row) => row.recipientName },
    { key: "phone", header: "Phone", accessor: (row) => row.phone },
    {
      key: "dateArrived",
      header: "Arrived",
      sortable: true,
      sortValue: (row) => row.dateArrived,
      accessor: (row) => format(new Date(row.dateArrived), "d MMM, HH:mm"),
    },
    {
      key: "daysWaiting",
      header: "Waiting",
      sortable: true,
      sortValue: (row) => row.daysWaiting,
      accessor: (row) => (
        <span className={cn(row.daysWaiting > OVERDUE_THRESHOLD_DAYS && "font-medium text-destructive")}>
          {row.daysWaiting}d
        </span>
      ),
    },
    { key: "status", header: "Status", accessor: (row) => <StatusBadge status={row.status} /> },
    {
      key: "action",
      header: "",
      accessor: (row) => (
        <Button size="sm" variant="outline" onClick={() => handleHandOver(row.id)}>
          Hand over
        </Button>
      ),
    },
  ];

  return (
    <div className="flex flex-col gap-6">
      <h1 className="font-heading text-xl font-semibold">Pickup dashboard</h1>

      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        <StatCard stat={{ label: "Awaiting pickup", value: inventory.length, icon: "ClipboardList" }} />
        <StatCard stat={{ label: "Checked in today", value: pickupSummary.checkedInToday, icon: "Truck" }} />
        <StatCard stat={{ label: "Checked out today", value: pickupSummary.checkedOutToday, icon: "CheckCircle2" }} />
        <StatCard stat={{ label: "Overdue", value: overdueCount, icon: "Clock" }} />
      </div>

      <form
        onSubmit={handleCheckIn}
        className="flex flex-col gap-2 rounded-[var(--radius-card)] border border-border bg-card p-4 sm:flex-row sm:items-end sm:gap-3"
      >
        <div className="flex flex-1 flex-col gap-1.5">
          <Label htmlFor="checkInId">Check in a parcel</Label>
          <Input
            id="checkInId"
            placeholder="Tracking ID, e.g. KE-2045"
            value={checkInId}
            onChange={(event) => setCheckInId(event.target.value)}
          />
        </div>
        <Button type="submit" className="h-9 gap-1.5">
          <PackageCheck size={16} aria-hidden="true" />
          Check in
        </Button>
      </form>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
        <div className="lg:col-span-2">
          <DataTable
            columns={columns}
            data={inventory}
            getRowId={(row) => row.id}
            searchable
            searchPlaceholder="Search by tracking ID or recipient"
            searchAccessor={(row) => `${row.id} ${row.recipientName}`}
            emptyMessage="No parcels awaiting pickup."
          />
        </div>
        <div className="flex flex-col gap-3 rounded-[var(--radius-card)] border border-border bg-card p-4">
          <h2 className="font-heading text-sm font-semibold">Recent activity</h2>
          <ul className="flex flex-col gap-3">
            {activity.map((event) => (
              <li key={event.id} className="flex items-start gap-2.5 text-sm">
                <span
                  className={cn(
                    "mt-0.5 flex size-6 shrink-0 items-center justify-center rounded-full",
                    event.type === "in"
                      ? "bg-success/15 text-success"
                      : "bg-info/15 text-info"
                  )}
                >
                  {event.type === "in" ? (
                    <ArrowDownToLine size={13} aria-hidden="true" />
                  ) : (
                    <ArrowUpFromLine size={13} aria-hidden="true" />
                  )}
                </span>
                <div className="flex flex-col">
                  <span>
                    {event.action} <span className="font-medium">{event.parcelId}</span>
                  </span>
                  <span className="text-xs text-muted-foreground">
                    {format(new Date(event.time), "d MMM, HH:mm")}
                  </span>
                </div>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
}

// src/app/modules/pickup/pages/pickup-dashboard/pickup-dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { ToastService } from '../../../../shared/services/toast.service';
import { ColumnConfig } from '../../../../shared/components/data-table/data-table.component';

interface InventoryItem {
  id: string;
  recipientName: string;
  phone: string;
  dateArrived: Date;
  daysWaiting: number;
  status: string;
}

interface ActivityEvent {
  time: Date;
  staff: string;
  action: string;
  parcelId: string;
  type: 'in' | 'out';
}

@Component({
  selector: 'app-pickup-dashboard',
  templateUrl: './pickup-dashboard.component.html',
  styleUrls: ['./pickup-dashboard.component.scss']
})
export class PickupDashboardComponent implements OnInit {
  checkInId = '';
  inventory: InventoryItem[] = [];
  activities: ActivityEvent[] = [];

  tableColumns: ColumnConfig[] = [
    { key: 'id', label: 'Tracking ID' },
    { key: 'recipientName', label: 'Recipient' },
    { key: 'phone', label: 'Phone' },
    { key: 'dateArrived', label: 'Date Arrived' },
    { key: 'daysWaiting', label: 'Days Waiting' },
    { key: 'status', label: 'Status', type: 'badge' },
    { key: 'action', label: 'Action', type: 'action' }
  ];

  constructor(private toast: ToastService) {}

  ngOnInit() {
    this.inventory = [
      { id: 'KE-2001', recipientName: 'Sarah J.', phone: '0712...', dateArrived: new Date(), daysWaiting: 0, status: 'pending' },
      { id: 'KE-1984', recipientName: 'Michael T.', phone: '0734...', dateArrived: new Date(Date.now() - 86400000 * 2), daysWaiting: 2, status: 'pending' },
      { id: 'KE-1900', recipientName: 'Evans K.', phone: '0799...', dateArrived: new Date(Date.now() - 86400000 * 4), daysWaiting: 4, status: 'failed' } // Overdue
    ];

    this.activities = [
      { time: new Date(Date.now() - 1200000), staff: 'You', action: 'Checked Out', parcelId: 'KE-1995', type: 'out' },
      { time: new Date(Date.now() - 3600000), staff: 'You', action: 'Checked In', parcelId: 'KE-2001', type: 'in' }
    ];
  }

  get awaitingCount() { return this.inventory.length; }
  get checkedInToday() { return 12; }
  get checkedOutToday() { return 45; }
  get overdueCount() { return this.inventory.filter(i => i.daysWaiting > 3).length; }

  onCheckIn() {
    if (!this.checkInId.trim()) {
      this.toast.error('Please enter a tracking ID');
      return;
    }
    
    // Simulate check-in
    const newItem: InventoryItem = {
      id: this.checkInId.toUpperCase(),
      recipientName: 'Walk-in Customer',
      phone: 'N/A',
      dateArrived: new Date(),
      daysWaiting: 0,
      status: 'pending'
    };
    
    this.inventory = [newItem, ...this.inventory];
    this.activities = [
      { time: new Date(), staff: 'You', action: 'Checked In', parcelId: newItem.id, type: 'in' },
      ...this.activities
    ];
    
    this.toast.success(`Parcel ${newItem.id} checked in successfully!`);
    this.checkInId = '';
  }
}

<div class="dashboard-root pickup-layout">
  
  <div class="dashboard-main">
    <app-navbar></app-navbar>

    <div class="dashboard-content stagger-1">
      
      <!-- Top Stats -->
      <div class="stats-row">
        <app-stat-card title="Awaiting Pickup" [value]="awaitingCount" icon="inventory_2"></app-stat-card>
        <app-stat-card title="Checked In Today" [value]="checkedInToday" icon="call_received" [change]="5"></app-stat-card>
        <app-stat-card title="Checked Out Today" [value]="checkedOutToday" icon="call_made" [change]="12"></app-stat-card>
        <app-stat-card title="Overdue (>3 days)" [value]="overdueCount" icon="warning" [change]="-1"></app-stat-card>
      </div>

      <div class="grid-layout">
        <div class="main-column">
          
          <!-- Actions Area -->
          <div class="actions-row">
            <!-- Manual Check-In -->
            <div class="checkin-panel glass-card hover-lift">
              <h3 class="sora-font">Manual Check-In</h3>
              <p class="subtitle">Enter tracking number manually</p>
              <div class="input-group">
                <mat-icon class="prefix-icon">qr_code_scanner</mat-icon>
                <input type="text" class="input-glow large-input" placeholder="e.g. KE-1234..." 
                       [(ngModel)]="checkInId" (keyup.enter)="onCheckIn()">
                <button class="btn-primary large-btn btn-scale" (click)="onCheckIn()">Check In</button>
              </div>
            </div>

            <!-- QR Scanner Placeholder -->
            <div class="qr-scanner-card glass-card hover-lift">
              <div class="scanner-frame">
                <mat-icon class="scan-icon pulse">center_focus_weak</mat-icon>
                <div class="scan-line"></div>
              </div>
              <div class="scanner-text">Scan Barcode / QR</div>
            </div>
          </div>

          <!-- Inventory Table -->
          <div class="inventory-section glass-card">
            <h2 class="section-title sora-font">Current Inventory</h2>
            <!-- Note: The TS DataTable component accepts standard data -->
            <!-- We customize row logic in CSS based on a global class but since data-table is encapsulated, we just show standard table here -->
            <app-data-table [columns]="tableColumns" [data]="inventory"></app-data-table>
          </div>

        </div>

        <!-- Activity Log -->
        <aside class="right-column glass-card overflow-auto">
          <h3 class="sora-font section-title">Today's Activity</h3>
          
          <div class="timeline-feed">
            <div class="timeline-item slide-in" *ngFor="let event of activities">
              <div class="timeline-marker" [ngClass]="event.type">
                <mat-icon>{{ event.type === 'in' ? 'call_received' : 'call_made' }}</mat-icon>
              </div>
              <div class="timeline-content">
                <div class="event-meta">
                  <span class="time">{{ event.time | date:'shortTime' }}</span>
                  <app-badge [status]="event.type === 'in' ? 'in-transit' : 'delivered'" [label]="event.action"></app-badge>
                </div>
                <div class="event-details">
                  <strong>{{ event.parcelId }}</strong> by {{ event.staff }}
                </div>
              </div>
            </div>
          </div>
        </aside>

      </div>

    </div>
  </div>
</div>
